### ISSUE TITLE
スコア評価結果を保存しておくdbの設計

### ISSUE THREAD

**Issue by EndoNrak** [ChallengeClub/tetris_score_server#37]
保存しておきたい項目
- ユーザーネーム（github リポジトリurl）
- 評価クエリ登録日時、評価開始、終了
- ブランチ名
- コメント
- レベル
- スタートコマンド（`python start.py`を実行するときのオプション類）
- 評価進行状況（評価待ち、評価中、エラー、評価終了など）
- 平均スコア、分散など
- ログファイル名（詳細な評価ログはs3に保存しておいて、dbにはそこへのリンクを貼っておく）

**Comment by EndoNrak** [comment]
AWS auroraを使った場合には最低でも月間で80-90ドルかかりそう
![image](https://user-images.githubusercontent.com/55904826/193036322-c2de9390-2135-45dc-8d1e-b78b1e87328c.png)

dynamo dbを使えば無料枠もあるし、最高でも月間10ドル以下でいけそう
![image](https://user-images.githubusercontent.com/55904826/193038589-d41995ef-36f7-40ff-bb2b-c945bc1198ac.png)


## ということでdynamo dbでデータベース設計していくことにした

**Comment by EndoNrak** [comment]
dbにアクセスする際のクエリユースケース（atcoderをイメージして）
- 全員の評価結果を日付順にならべて閲覧する　←デフォルトの表示形式
- ユーザー名で検索して評価結果を閲覧する　←一番頻度高そう
- レベルを指定してスコアの高かった評価結果を見る

**Comment by EndoNrak** [comment]
テーブル設計
[dynamodbベストプラクティス](https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/developerguide/best-practices.html)を参考にした
- 評価ID （パーティションキー）
- 評価登録日時(int型のunix時間)　（ソートキー）
- ユーザー主体検索用インデックス（GSI）
　- ユーザーリポジトリurl （パーティションキー）
　- 評価登録日時(int型のunix時間)　（ソートキー）
- レベル主体検索用インデックス（GSI）
　- レベル （パーティションキー）
　- 平均スコア（ソートキー）

**Comment by seigot** [comment]
> AWS auroraを使った場合には最低でも月間で80-90ドルかかりそう

高いですね、、

> dynamo dbを使えば無料枠もあるし、最高でも月間10ドル以下でいけそう

価格が全然違いますね、、

**Comment by EndoNrak** [comment]
#38 で機能要件を満たした
